### ISSUE TITLE
Bring this up to date (6.2...)

### ISSUE THREAD

**Issue by pastorryanhayden** [dannyweeks/october-theme-blank-foundation-6#1]
First, this is an awesome theme.  Thank you.  I'm in the process of porting a bunch of themes I developed in Foundation for jekyll over to October and this is very helpful.
But I'm struggling to get some of the settings and javascript to work and I think it's because this theme is based on 6.0.0 and foundation is up to 6.2 at this point.  
Again, thanks and good work.

**Comment by dannyweeks** [comment]
Sorry but I no longer use this theme so have no intention of supporting but would happily accept PRs
